version: '3.8'

services:
  backend:
    build: .
    image: theneonwhale/space2study-backend:latest
    container_name: space2study-backend
    ports:
      - "3000:3000"
    env_file:
      - /home/ec2-user/app/.env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
