global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'space2study-backend'
    ec2_sd_configs:
      - region: 'us-east-1'
        port: 3000
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: 'space2study-backend'
        action: keep
