name: CD

on:
  push:
    branches: [ develop ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    outputs:
      backend_public_ip: ${{ steps.instance_ip.outputs.ip }}
      backend_secret_id: ${{ steps.backend_secret_id.outputs.id }}
      aws_region: ${{ steps.aws_region.outputs.region }}
      s3_bucket_name: ${{ steps.s3_bucket_name.outputs.name }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Or your desired region

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./terraform

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve -var 'allowed_ip_addresses=${{ secrets.ALLOWED_IP_ADDRESSES }}'
        working-directory: ./terraform
        env:
          TF_VAR_mail_user: ${{ secrets.MAIL_USER }}
          TF_VAR_gmail_client_id: ${{ secrets.GMAIL_CLIENT_ID }}
          TF_VAR_gmail_client_secret: ${{ secrets.GMAIL_CLIENT_SECRET }}
          TF_VAR_gmail_refresh_token: ${{ secrets.GMAIL_REFRESH_TOKEN }}

      - name: 'Get instance IP'
        id: instance_ip
        run: echo "::set-output name=ip::$(terraform output -raw backend_public_ip)"
        working-directory: ./terraform

      - name: 'Get backend secret id'
        id: backend_secret_id
        run: echo "::set-output name=id::$(terraform output -raw backend_secret_id)"
        working-directory: ./terraform

      - name: 'Get aws region'
        id: aws_region
        run: echo "::set-output name=region::$(terraform output -raw aws_region)"
        working-directory: ./terraform

      - name: 'Get s3 bucket name'
        id: s3_bucket_name
        run: echo "::set-output name=name::$(terraform output -raw s3_bucket_name)"
        working-directory: ./terraform

  ansible:
    name: 'Ansible'
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout backend repository'
        uses: actions/checkout@v4
        with:
          path: backend

      - name: 'Checkout frontend repository'
        uses: actions/checkout@v4
        with:
          repository: theneonwhale/space2study-frontend-devops
          path: frontend

      - name: 'Run Ansible Playbook'
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          directory: ./backend/ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [aws_ec2]
            ${{ needs.terraform.outputs.backend_public_ip }} ansible_user=ubuntu
          extra_vars: |
            backend_secret_id=${{ needs.terraform.outputs.backend_secret_id }}
            aws_region=${{ needs.terraform.outputs.aws_region }}
            s3_bucket_name=${{ needs.terraform.outputs.s3_bucket_name }}
            backend_public_ip=${{ needs.terraform.outputs.backend_public_ip }}
            frontend_repository_path=${{ github.workspace }}/frontend
