
name: CI/CD

on: [push, pull_request]

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        env:
          MONGODB_URL: mongodb://localhost:27017/test
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          JWT_RESET_SECRET: ${{ secrets.JWT_RESET_SECRET }}
          JWT_CONFIRM_SECRET: ${{ secrets.JWT_CONFIRM_SECRET }}
          JWT_ACCESS_EXPIRES_IN: 1h
          JWT_REFRESH_EXPIRES_IN: 1d
          SUPERADMIN_FIRST_NAME: ${{ secrets.SUPERADMIN_FIRSTNAME }}
          SUPERADMIN_LAST_NAME: ${{ secrets.SUPERADMIN_LASTNAME }}
          SUPERADMIN_EMAIL: ${{ secrets.SUPERADMIN_EMAIL }}
          SUPERADMIN_PASSWORD: ${{ secrets.SUPERADMIN_PASSWORD }}
        run: npm test

  deploy:
    name: 'Deploy'
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 'Create S3 Backend Bucket if it does not exist'
        run: |
          aws s3api head-bucket --bucket space2study-backend-devops-tfstate 2>/dev/null || aws s3api create-bucket --bucket space2study-backend-devops-tfstate --region us-east-1

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./terraform

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          TF_VAR_allowed_ip_addresses: ${{ secrets.ALLOWED_IP_ADDRESSES }}
          TF_VAR_mongodb_atlas_public_key: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
          TF_VAR_mongodb_atlas_private_key: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
          TF_VAR_mongodb_atlas_org_id: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
          TF_VAR_superadmin_firstname: ${{ secrets.SUPERADMIN_FIRSTNAME }}
          TF_VAR_superadmin_lastname: ${{ secrets.SUPERADMIN_LASTNAME }}
          TF_VAR_superadmin_email: ${{ secrets.SUPERADMIN_EMAIL }}
          TF_VAR_superadmin_password: ${{ secrets.SUPERADMIN_PASSWORD }}
          TF_VAR_mail_user: ${{ secrets.MAIL_USER }}
          TF_VAR_gmail_client_id: ${{ secrets.GMAIL_CLIENT_ID }}
          TF_VAR_gmail_client_secret: ${{ secrets.GMAIL_CLIENT_SECRET }}
          TF_VAR_gmail_refresh_token: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          TF_VAR_jwt_access_secret: ${{ secrets.JWT_ACCESS_SECRET }}
          TF_VAR_jwt_refresh_secret: ${{ secrets.JWT_REFRESH_SECRET }}
          TF_VAR_jwt_reset_secret: ${{ secrets.JWT_RESET_SECRET }}
          TF_VAR_jwt_confirm_secret: ${{ secrets.JWT_CONFIRM_SECRET }}

      - name: 'Get instance IP'
        id: instance_ip
        run: echo "::set-output name=ip::$(terraform output -raw backend_public_ip)"
        working-directory: ./terraform

      - name: 'Get backend secret id'
        id: backend_secret_id
        run: echo "::set-output name=id::$(terraform output -raw backend_secret_id)"
        working-directory: ./terraform

      - name: 'Get aws region'
        id: aws_region
        run: echo "::set-output name=region::$(terraform output -raw aws_region)"
        working-directory: ./terraform

      - name: 'Get s3 bucket name'
        id: s3_bucket_name
        run: echo "::set-output name=name::$(terraform output -raw s3_bucket_name)"
        working-directory: ./terraform

      - name: 'Checkout backend repository'
        uses: actions/checkout@v4
        with:
          path: backend

      - name: 'Checkout frontend repository'
        uses: actions/checkout@v4
        with:
          repository: theneonwhale/space2study-frontend-devops
          path: frontend

      - name: 'Remove backend ESLint config to prevent conflict'
        run: rm ./.eslintrc.json

      - name: 'Run Ansible Playbook'
        uses: dawidd6/action-ansible-playbook@v4
        with:
          playbook: main.yml
          directory: ./ansible
          requirements: requirements.txt
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [aws_ec2]
            ${{ steps.instance_ip.outputs.ip }} ansible_user=ec2-user
          options: |
            --extra-vars "backend_secret_id=${{ steps.backend_secret_id.outputs.id }} aws_region=${{ steps.aws_region.outputs.region }} s3_bucket_name=${{ steps.s3_bucket_name.outputs.name }} backend_public_ip=${{ steps.instance_ip.outputs.ip }} frontend_repository_path=${{ github.workspace }}/frontend"
